-- Seed activities (32 total)
INSERT INTO activities (name, type, default_minutes) VALUES
  ('Rabbit', 'Home', 5),
  ('Folding', 'Home', 10),
  ('Laundry', 'Home', 5),
  ('Clean upstairs bathroom', 'Home', 20),
  ('Clean downstairs bathroom', 'Home', 20),
  ('Vacuum & tidy front room', 'Home', 10),
  ('Vacuum & tidy dining room', 'Home', 10),
  ('Vacuum stairs & landing', 'Home', 5),
  ('Vacuum own bedroom', 'Home', 15),
  ('Purge fridge & menu', 'Home', 30),
  ('Grocery shopping', 'Home', 30),
  ('Deep clean kitchen', 'Home', 30),
  ('Tidy basement', 'Home', 30),
  ('Change bed sheets - Thomas', 'Home', 10),
  ('Change bed sheets - Boys', 'Home', 15),
  ('Outside (mow, weed, rake)', 'Home', 60),
  ('D&D', 'Brain', 60),
  ('Science bowl', 'Brain', 60),
  ('Cello practice', 'Brain', 20),
  ('Cello MYS', 'Brain', 120),
  ('Cello lesson', 'Brain', 45),
  ('Math practice', 'Brain', 30),
  ('Robotics', 'Brain', 90),
  ('Guitar', 'Brain', 60),
  ('Squash', 'Body', 90),
  ('Stretches', 'Body', 15),
  ('Family Hike', 'Body', 120),
  ('Ivor exercise', 'Body', 60),
  ('Axel exercise', 'Body', 60),
  ('Video Downtime', 'Downtime', 30),
  ('Family Video / Read', 'Downtime', 30),
  ('Non video downtime', 'Downtime', 30);
